apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-otsugua-srv2
  namespace: otsugua04-dev
  labels:
    app: mi-app-otsugua-srv2
    areanegocio: tecnologia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app-otsugua-srv2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mi-app-otsugua-srv2
    spec:
      containers:
      - name: mi-app-container
        image: otsugua04/hola-mundo-service2:build-{{ tag }} 
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 800m
            memory: 1500Mi
        envFrom:
            - configMapRef:
                name: mi-configmap-otsugua-srv2
            - secretRef:
                name: mi-secret-otsugua-srv2
        startupProbe:
          httpGet:
            path: /startup
            port: 3000
          failureThreshold: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3000
          failureThreshold: 5
          initialDelaySeconds: 0
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          failureThreshold: 5
          initialDelaySeconds: 0
          periodSeconds: 10
---

apiVersion: v1
kind: Service
metadata:
  name: mi-servicio-otsugua-srv2
  namespace: otsugua04-dev
spec:
  selector:
    app: mi-app-otsugua-srv2
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 3000
  type: ClusterIP

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mi-configmap-otsugua-srv2
  namespace: otsugua04-dev
data:
    DATABASE: "192.168.1.1"

---

apiVersion: v1
kind: Secret
metadata:
  name: mi-secret-otsugua-srv2
  namespace: otsugua04-dev
type: Opaque
data:
    PASSWORD: cGFzc3dvcmRwcnVlYmE=

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mi-hpa-srv2
  namespace: otsugua04-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: mi-app-otsugua-srv2
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otsugua-pvc-srv2
  namespace: otsugua04-dev
spec:
  accessModes:
     - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 1Gi
