name: microservicio-2

namespace: otsugua04-dev

container:
  tag: "{{ tag }}"
  port: 3000
  image: "otsugua04/hola-mundo-service2"
  replicas: 2
  cpuRequests: "500m"
  memRequests: "800Mi"
  cpuLimits: "1000m"
  memLimits: "1500Mi"

service:
  type: ClusterIP
  port: 4000
  targetPort: 3000

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75

configmap:
  database: "192.168.1.1"

secret:
  # plain text password; template will base64-encode when placing into `data:`
  password: "hola"